# generated : 2018-07-25:08:48  // template : ./setup/service_down.sh.jinja2

export CURRENT_UID="$(id -u):$(id -g)" 


 docker-compose stop taginfo-eu-ad
 docker-compose stop taginfo-eu-al
 docker-compose stop taginfo-eu-at
 docker-compose stop taginfo-eu-ax
 docker-compose stop taginfo-eu-ba
 docker-compose stop taginfo-eu-be
 docker-compose stop taginfo-eu-bg
 docker-compose stop taginfo-eu-by
 docker-compose stop taginfo-eu-ch
 docker-compose stop taginfo-eu-cy
 docker-compose stop taginfo-eu-cz
 docker-compose stop taginfo-eu-de-bb
 docker-compose stop taginfo-eu-de-be
 docker-compose stop taginfo-eu-de-bw
 docker-compose stop taginfo-eu-de-by
 docker-compose stop taginfo-eu-de-hb
 docker-compose stop taginfo-eu-de-he
 docker-compose stop taginfo-eu-de-hh
 docker-compose stop taginfo-eu-de-mv
 docker-compose stop taginfo-eu-de-ni
 docker-compose stop taginfo-eu-de-nw
 docker-compose stop taginfo-eu-de-rp
 docker-compose stop taginfo-eu-de-sh
 docker-compose stop taginfo-eu-de-sl
 docker-compose stop taginfo-eu-de-sn
 docker-compose stop taginfo-eu-de-st
 docker-compose stop taginfo-eu-de-th
 docker-compose stop taginfo-eu-dk
 docker-compose stop taginfo-eu-ee
 docker-compose stop taginfo-eu-es
 docker-compose stop taginfo-eu-fi
 docker-compose stop taginfo-eu-fo
 docker-compose stop taginfo-eu-fr-01
 docker-compose stop taginfo-eu-fr-02
 docker-compose stop taginfo-eu-fr-03
 docker-compose stop taginfo-eu-fr-04
 docker-compose stop taginfo-eu-fr-05
 docker-compose stop taginfo-eu-fr-06
 docker-compose stop taginfo-eu-fr-07
 docker-compose stop taginfo-eu-fr-08
 docker-compose stop taginfo-eu-fr-09
 docker-compose stop taginfo-eu-fr-10
 docker-compose stop taginfo-eu-fr-11
 docker-compose stop taginfo-eu-fr-12
 docker-compose stop taginfo-eu-fr-13
 docker-compose stop taginfo-eu-fr-14
 docker-compose stop taginfo-eu-fr-15
 docker-compose stop taginfo-eu-fr-16
 docker-compose stop taginfo-eu-fr-17
 docker-compose stop taginfo-eu-fr-18
 docker-compose stop taginfo-eu-fr-19
 docker-compose stop taginfo-eu-fr-21
 docker-compose stop taginfo-eu-fr-22
 docker-compose stop taginfo-eu-fr-23
 docker-compose stop taginfo-eu-fr-24
 docker-compose stop taginfo-eu-fr-25
 docker-compose stop taginfo-eu-fr-26
 docker-compose stop taginfo-eu-fr-27
 docker-compose stop taginfo-eu-fr-28
 docker-compose stop taginfo-eu-fr-29
 docker-compose stop taginfo-eu-fr-2a
 docker-compose stop taginfo-eu-fr-2b
 docker-compose stop taginfo-eu-fr-30
 docker-compose stop taginfo-eu-fr-31
 docker-compose stop taginfo-eu-fr-32
 docker-compose stop taginfo-eu-fr-33
 docker-compose stop taginfo-eu-fr-34
 docker-compose stop taginfo-eu-fr-35
 docker-compose stop taginfo-eu-fr-36
 docker-compose stop taginfo-eu-fr-37
 docker-compose stop taginfo-eu-fr-38
 docker-compose stop taginfo-eu-fr-39
 docker-compose stop taginfo-eu-fr-40
 docker-compose stop taginfo-eu-fr-41
 docker-compose stop taginfo-eu-fr-42
 docker-compose stop taginfo-eu-fr-43
 docker-compose stop taginfo-eu-fr-44
 docker-compose stop taginfo-eu-fr-45
 docker-compose stop taginfo-eu-fr-46
 docker-compose stop taginfo-eu-fr-47
 docker-compose stop taginfo-eu-fr-48
 docker-compose stop taginfo-eu-fr-49
 docker-compose stop taginfo-eu-fr-50
 docker-compose stop taginfo-eu-fr-51
 docker-compose stop taginfo-eu-fr-52
 docker-compose stop taginfo-eu-fr-53
 docker-compose stop taginfo-eu-fr-54
 docker-compose stop taginfo-eu-fr-55
 docker-compose stop taginfo-eu-fr-56
 docker-compose stop taginfo-eu-fr-57
 docker-compose stop taginfo-eu-fr-58
 docker-compose stop taginfo-eu-fr-59
 docker-compose stop taginfo-eu-fr-60
 docker-compose stop taginfo-eu-fr-61
 docker-compose stop taginfo-eu-fr-62
 docker-compose stop taginfo-eu-fr-63
 docker-compose stop taginfo-eu-fr-64
 docker-compose stop taginfo-eu-fr-65
 docker-compose stop taginfo-eu-fr-66
 docker-compose stop taginfo-eu-fr-67
 docker-compose stop taginfo-eu-fr-68
 docker-compose stop taginfo-eu-fr-69
 docker-compose stop taginfo-eu-fr-70
 docker-compose stop taginfo-eu-fr-71
 docker-compose stop taginfo-eu-fr-72
 docker-compose stop taginfo-eu-fr-73
 docker-compose stop taginfo-eu-fr-74
 docker-compose stop taginfo-eu-fr-75
 docker-compose stop taginfo-eu-fr-76
 docker-compose stop taginfo-eu-fr-77
 docker-compose stop taginfo-eu-fr-78
 docker-compose stop taginfo-eu-fr-79
 docker-compose stop taginfo-eu-fr-80
 docker-compose stop taginfo-eu-fr-81
 docker-compose stop taginfo-eu-fr-82
 docker-compose stop taginfo-eu-fr-83
 docker-compose stop taginfo-eu-fr-84
 docker-compose stop taginfo-eu-fr-85
 docker-compose stop taginfo-eu-fr-86
 docker-compose stop taginfo-eu-fr-87
 docker-compose stop taginfo-eu-fr-88
 docker-compose stop taginfo-eu-fr-89
 docker-compose stop taginfo-eu-fr-90
 docker-compose stop taginfo-eu-fr-91
 docker-compose stop taginfo-eu-fr-92
 docker-compose stop taginfo-eu-fr-93
 docker-compose stop taginfo-eu-fr-94
 docker-compose stop taginfo-eu-fr-95
 docker-compose stop taginfo-eu-fr-ara
 docker-compose stop taginfo-eu-fr-bfc
 docker-compose stop taginfo-eu-fr-bre
 docker-compose stop taginfo-eu-fr-cor
 docker-compose stop taginfo-eu-fr-cvl
 docker-compose stop taginfo-eu-fr-ges
 docker-compose stop taginfo-eu-fr-hdf
 docker-compose stop taginfo-eu-fr-idf
 docker-compose stop taginfo-eu-fr-naq
 docker-compose stop taginfo-eu-fr-nor
 docker-compose stop taginfo-eu-fr-occ
 docker-compose stop taginfo-eu-fr-pac
 docker-compose stop taginfo-eu-fr-pdl
 docker-compose stop taginfo-eu-gb
 docker-compose stop taginfo-eu-ge
 docker-compose stop taginfo-eu-gg
 docker-compose stop taginfo-eu-gi
 docker-compose stop taginfo-eu-gr
 docker-compose stop taginfo-eu-hr
 docker-compose stop taginfo-eu-hu
 docker-compose stop taginfo-eu-ie
 docker-compose stop taginfo-eu-im
 docker-compose stop taginfo-eu-is
 docker-compose stop taginfo-eu-it
 docker-compose stop taginfo-eu-it-32
 docker-compose stop taginfo-eu-it-88
 docker-compose stop taginfo-eu-je
 docker-compose stop taginfo-eu-li
 docker-compose stop taginfo-eu-lt
 docker-compose stop taginfo-eu-lu
 docker-compose stop taginfo-eu-lv
 docker-compose stop taginfo-eu-mc
 docker-compose stop taginfo-eu-md
 docker-compose stop taginfo-eu-me
 docker-compose stop taginfo-eu-mk
 docker-compose stop taginfo-eu-mt
 docker-compose stop taginfo-eu-nl
 docker-compose stop taginfo-eu-nl-dr
 docker-compose stop taginfo-eu-nl-fl
 docker-compose stop taginfo-eu-nl-fr
 docker-compose stop taginfo-eu-nl-ge
 docker-compose stop taginfo-eu-nl-gr
 docker-compose stop taginfo-eu-nl-li
 docker-compose stop taginfo-eu-nl-nb
 docker-compose stop taginfo-eu-nl-nh
 docker-compose stop taginfo-eu-nl-ov
 docker-compose stop taginfo-eu-nl-ut
 docker-compose stop taginfo-eu-nl-ze
 docker-compose stop taginfo-eu-nl-zh
 docker-compose stop taginfo-eu-no
 docker-compose stop taginfo-eu-pl
 docker-compose stop taginfo-eu-pt
 docker-compose stop taginfo-eu-ro
 docker-compose stop taginfo-eu-rs
 docker-compose stop taginfo-eu-se
 docker-compose stop taginfo-eu-si
 docker-compose stop taginfo-eu-sk
 docker-compose stop taginfo-eu-sm
 docker-compose stop taginfo-eu-tr
 docker-compose stop taginfo-eu-ua
 docker-compose stop taginfo-eu-va
 docker-compose stop taginfo-eu-xk
 
# generated : 2018-07-25:08:48