sudo: required

services:
  - docker

before_install:
  - docker-compose -v
  - docker -v
	- docker pull ruby:2.5-alpine3.7
	- docker pull mdillon/postgis:10
	- docker pull ubuntu:18.04
  - docker images
  
script:
  - docker-compose config
  - make test
  
