# generated : 2018-07-25:09:10  // template : ./setup/template/Makefile.jinja2

CURRENT_UID:=$(shell echo $$(id -u):$$(id -g))
export CURRENT_UID

down:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose down

clean:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose rm -f -v


taginfo-na-bm:
	# make GDNAME=north-america taginfo-na-bm
	@echo " Start test  na-bm :: Bermuda     ::     mapped local port after finishing   127.0.0.1:22001"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-bm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-bm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-bm

taginfo-na-ca-ab:
	# make GDNAME=canada taginfo-na-ca-ab
	@echo " Start test  na-ca-ab :: Alberta     ::     mapped local port after finishing   127.0.0.1:22002"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-ca-ab	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-ca-ab /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-ca-ab

taginfo-na-ca-bc:
	# make GDNAME=north-america taginfo-na-ca-bc
	@echo " Start test  na-ca-bc :: British Columbia     ::     mapped local port after finishing   127.0.0.1:22003"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-ca-bc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-ca-bc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-ca-bc

taginfo-na-ca-mb:
	# make GDNAME=manitoba taginfo-na-ca-mb
	@echo " Start test  na-ca-mb :: Manitoba     ::     mapped local port after finishing   127.0.0.1:22004"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-ca-mb	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-ca-mb /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-ca-mb

taginfo-na-ca-nb:
	# make GDNAME=north-america taginfo-na-ca-nb
	@echo " Start test  na-ca-nb :: New Brunswick     ::     mapped local port after finishing   127.0.0.1:22005"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-ca-nb	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-ca-nb /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-ca-nb

taginfo-na-ca-nl:
	# make GDNAME=newfoundland-and-labrador taginfo-na-ca-nl
	@echo " Start test  na-ca-nl :: Newfoundland and Labrador     ::     mapped local port after finishing   127.0.0.1:22006"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-ca-nl	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-ca-nl /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-ca-nl

taginfo-na-ca-ns:
	# make GDNAME=nova-scotia taginfo-na-ca-ns
	@echo " Start test  na-ca-ns :: Nova Scotia     ::     mapped local port after finishing   127.0.0.1:22007"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-ca-ns	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-ca-ns /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-ca-ns

taginfo-na-ca-nt:
	# make GDNAME=canada taginfo-na-ca-nt
	@echo " Start test  na-ca-nt :: Northwest Territories     ::     mapped local port after finishing   127.0.0.1:22008"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-ca-nt	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-ca-nt /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-ca-nt

taginfo-na-ca-nu:
	# make GDNAME=north-america taginfo-na-ca-nu
	@echo " Start test  na-ca-nu :: Nunavut     ::     mapped local port after finishing   127.0.0.1:22009"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-ca-nu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-ca-nu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-ca-nu

taginfo-na-ca-on:
	# make GDNAME=north-america taginfo-na-ca-on
	@echo " Start test  na-ca-on :: Ontario     ::     mapped local port after finishing   127.0.0.1:22010"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-ca-on	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-ca-on /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-ca-on

taginfo-na-ca-pe:
	# make GDNAME=canada taginfo-na-ca-pe
	@echo " Start test  na-ca-pe :: Prince Edward Island     ::     mapped local port after finishing   127.0.0.1:22011"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-ca-pe	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-ca-pe /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-ca-pe

taginfo-na-ca-qc:
	# make GDNAME=north-america taginfo-na-ca-qc
	@echo " Start test  na-ca-qc :: Quebec     ::     mapped local port after finishing   127.0.0.1:22012"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-ca-qc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-ca-qc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-ca-qc

taginfo-na-ca-sk:
	# make GDNAME=saskatchewan taginfo-na-ca-sk
	@echo " Start test  na-ca-sk :: Saskatchewan     ::     mapped local port after finishing   127.0.0.1:22013"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-ca-sk	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-ca-sk /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-ca-sk

taginfo-na-ca-yt:
	# make GDNAME=canada taginfo-na-ca-yt
	@echo " Start test  na-ca-yt :: Yukon     ::     mapped local port after finishing   127.0.0.1:22014"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-ca-yt	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-ca-yt /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-ca-yt

taginfo-na-fr-pm:
	# make GDNAME=canada taginfo-na-fr-pm
	@echo " Start test  na-fr-pm :: Saint Pierre and Miquelon     ::     mapped local port after finishing   127.0.0.1:22015"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-fr-pm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-fr-pm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-fr-pm

taginfo-na-gl:
	# make GDNAME=greenland taginfo-na-gl
	@echo " Start test  na-gl :: Greenland     ::     mapped local port after finishing   127.0.0.1:22016"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-gl	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-gl /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-gl

taginfo-na-mx:
	# make GDNAME=north-america taginfo-na-mx
	@echo " Start test  na-mx :: Mexico     ::     mapped local port after finishing   127.0.0.1:22017"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-mx	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-mx /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-mx

taginfo-na-us-ak:
	# make GDNAME=north-america taginfo-na-us-ak
	@echo " Start test  na-us-ak :: Alaska     ::     mapped local port after finishing   127.0.0.1:22018"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ak	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ak /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ak

taginfo-na-us-al:
	# make GDNAME=us-south taginfo-na-us-al
	@echo " Start test  na-us-al :: Alabama     ::     mapped local port after finishing   127.0.0.1:22019"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-al	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-al /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-al

taginfo-na-us-ar:
	# make GDNAME=us-south taginfo-na-us-ar
	@echo " Start test  na-us-ar :: Arkansas     ::     mapped local port after finishing   127.0.0.1:22020"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ar	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ar /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ar

taginfo-na-us-az:
	# make GDNAME=north-america taginfo-na-us-az
	@echo " Start test  na-us-az :: Arizona     ::     mapped local port after finishing   127.0.0.1:22021"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-az	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-az /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-az

taginfo-na-us-ca:
	# make GDNAME=california taginfo-na-us-ca
	@echo " Start test  na-us-ca :: California     ::     mapped local port after finishing   127.0.0.1:22022"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ca	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ca /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ca

taginfo-na-us-co:
	# make GDNAME=north-america taginfo-na-us-co
	@echo " Start test  na-us-co :: Colorado     ::     mapped local port after finishing   127.0.0.1:22023"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-co	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-co /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-co

taginfo-na-us-ct:
	# make GDNAME=us-northeast taginfo-na-us-ct
	@echo " Start test  na-us-ct :: Connecticut     ::     mapped local port after finishing   127.0.0.1:22024"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ct	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ct /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ct

taginfo-na-us-dc:
	# make GDNAME=us-south taginfo-na-us-dc
	@echo " Start test  na-us-dc :: District of Columbia     ::     mapped local port after finishing   127.0.0.1:22025"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-dc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-dc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-dc

taginfo-na-us-de:
	# make GDNAME=us-south taginfo-na-us-de
	@echo " Start test  na-us-de :: Delaware     ::     mapped local port after finishing   127.0.0.1:22026"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-de	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-de /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-de

taginfo-na-us-fl:
	# make GDNAME=florida taginfo-na-us-fl
	@echo " Start test  na-us-fl :: Florida     ::     mapped local port after finishing   127.0.0.1:22027"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-fl	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-fl /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-fl

taginfo-na-us-ga:
	# make GDNAME=us-south taginfo-na-us-ga
	@echo " Start test  na-us-ga :: Georgia     ::     mapped local port after finishing   127.0.0.1:22028"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ga	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ga /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ga

taginfo-na-us-hi:
	# make GDNAME=us-pacific taginfo-na-us-hi
	@echo " Start test  na-us-hi :: Hawaii     ::     mapped local port after finishing   127.0.0.1:22029"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-hi	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-hi /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-hi

taginfo-na-us-ia:
	# make GDNAME=us-midwest taginfo-na-us-ia
	@echo " Start test  na-us-ia :: Iowa     ::     mapped local port after finishing   127.0.0.1:22030"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ia	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ia /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ia

taginfo-na-us-id:
	# make GDNAME=us-west taginfo-na-us-id
	@echo " Start test  na-us-id :: Idaho     ::     mapped local port after finishing   127.0.0.1:22031"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-id	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-id /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-id

taginfo-na-us-il:
	# make GDNAME=us-midwest taginfo-na-us-il
	@echo " Start test  na-us-il :: Illinois     ::     mapped local port after finishing   127.0.0.1:22032"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-il	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-il /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-il

taginfo-na-us-in:
	# make GDNAME=north-america taginfo-na-us-in
	@echo " Start test  na-us-in :: Indiana     ::     mapped local port after finishing   127.0.0.1:22033"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-in	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-in /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-in

taginfo-na-us-ks:
	# make GDNAME=us-midwest taginfo-na-us-ks
	@echo " Start test  na-us-ks :: Kansas     ::     mapped local port after finishing   127.0.0.1:22034"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ks	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ks /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ks

taginfo-na-us-ky:
	# make GDNAME=north-america taginfo-na-us-ky
	@echo " Start test  na-us-ky :: Kentucky     ::     mapped local port after finishing   127.0.0.1:22035"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ky	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ky /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ky

taginfo-na-us-la:
	# make GDNAME=us-south taginfo-na-us-la
	@echo " Start test  na-us-la :: Louisiana     ::     mapped local port after finishing   127.0.0.1:22036"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-la	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-la /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-la

taginfo-na-us-ma:
	# make GDNAME=north-america taginfo-na-us-ma
	@echo " Start test  na-us-ma :: Massachusetts     ::     mapped local port after finishing   127.0.0.1:22037"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ma	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ma /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ma

taginfo-na-us-md:
	# make GDNAME=us-south taginfo-na-us-md
	@echo " Start test  na-us-md :: Maryland     ::     mapped local port after finishing   127.0.0.1:22038"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-md	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-md /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-md

taginfo-na-us-me:
	# make GDNAME=us-northeast taginfo-na-us-me
	@echo " Start test  na-us-me :: Maine     ::     mapped local port after finishing   127.0.0.1:22039"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-me	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-me /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-me

taginfo-na-us-mi:
	# make GDNAME=north-america taginfo-na-us-mi
	@echo " Start test  na-us-mi :: Michigan     ::     mapped local port after finishing   127.0.0.1:22040"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-mi	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-mi /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-mi

taginfo-na-us-mn:
	# make GDNAME=us-midwest taginfo-na-us-mn
	@echo " Start test  na-us-mn :: Minnesota     ::     mapped local port after finishing   127.0.0.1:22041"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-mn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-mn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-mn

taginfo-na-us-mo:
	# make GDNAME=us-midwest taginfo-na-us-mo
	@echo " Start test  na-us-mo :: Missouri     ::     mapped local port after finishing   127.0.0.1:22042"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-mo	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-mo /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-mo

taginfo-na-us-ms:
	# make GDNAME=us-south taginfo-na-us-ms
	@echo " Start test  na-us-ms :: Mississippi     ::     mapped local port after finishing   127.0.0.1:22043"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ms	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ms /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ms

taginfo-na-us-mt:
	# make GDNAME=north-america taginfo-na-us-mt
	@echo " Start test  na-us-mt :: Montana     ::     mapped local port after finishing   127.0.0.1:22044"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-mt	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-mt /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-mt

taginfo-na-us-nc:
	# make GDNAME=us-south taginfo-na-us-nc
	@echo " Start test  na-us-nc :: North Carolina     ::     mapped local port after finishing   127.0.0.1:22045"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-nc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-nc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-nc

taginfo-na-us-nd:
	# make GDNAME=north-america taginfo-na-us-nd
	@echo " Start test  na-us-nd :: North Dakota     ::     mapped local port after finishing   127.0.0.1:22046"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-nd	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-nd /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-nd

taginfo-na-us-ne:
	# make GDNAME=north-america taginfo-na-us-ne
	@echo " Start test  na-us-ne :: Nebraska     ::     mapped local port after finishing   127.0.0.1:22047"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ne	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ne /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ne

taginfo-na-us-nh:
	# make GDNAME=north-america taginfo-na-us-nh
	@echo " Start test  na-us-nh :: New Hampshire     ::     mapped local port after finishing   127.0.0.1:22048"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-nh	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-nh /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-nh

taginfo-na-us-nj:
	# make GDNAME=north-america taginfo-na-us-nj
	@echo " Start test  na-us-nj :: New Jersey     ::     mapped local port after finishing   127.0.0.1:22049"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-nj	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-nj /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-nj

taginfo-na-us-nm:
	# make GDNAME=north-america taginfo-na-us-nm
	@echo " Start test  na-us-nm :: New Mexico     ::     mapped local port after finishing   127.0.0.1:22050"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-nm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-nm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-nm

taginfo-na-us-nv:
	# make GDNAME=us-west taginfo-na-us-nv
	@echo " Start test  na-us-nv :: Nevada     ::     mapped local port after finishing   127.0.0.1:22051"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-nv	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-nv /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-nv

taginfo-na-us-ny:
	# make GDNAME=north-america taginfo-na-us-ny
	@echo " Start test  na-us-ny :: New York     ::     mapped local port after finishing   127.0.0.1:22052"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ny	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ny /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ny

taginfo-na-us-oh:
	# make GDNAME=north-america taginfo-na-us-oh
	@echo " Start test  na-us-oh :: Ohio     ::     mapped local port after finishing   127.0.0.1:22053"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-oh	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-oh /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-oh

taginfo-na-us-ok:
	# make GDNAME=north-america taginfo-na-us-ok
	@echo " Start test  na-us-ok :: Oklahoma     ::     mapped local port after finishing   127.0.0.1:22054"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ok	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ok /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ok

taginfo-na-us-or:
	# make GDNAME=us-west taginfo-na-us-or
	@echo " Start test  na-us-or :: Oregon     ::     mapped local port after finishing   127.0.0.1:22055"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-or	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-or /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-or

taginfo-na-us-pa:
	# make GDNAME=us-northeast taginfo-na-us-pa
	@echo " Start test  na-us-pa :: Pennsylvania     ::     mapped local port after finishing   127.0.0.1:22056"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-pa	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-pa /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-pa

taginfo-na-us-ri:
	# make GDNAME=us-northeast taginfo-na-us-ri
	@echo " Start test  na-us-ri :: Rhode Island     ::     mapped local port after finishing   127.0.0.1:22057"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ri	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ri /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ri

taginfo-na-us-sc:
	# make GDNAME=us-south taginfo-na-us-sc
	@echo " Start test  na-us-sc :: South Carolina     ::     mapped local port after finishing   127.0.0.1:22058"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-sc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-sc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-sc

taginfo-na-us-sd:
	# make GDNAME=north-america taginfo-na-us-sd
	@echo " Start test  na-us-sd :: South Dakota     ::     mapped local port after finishing   127.0.0.1:22059"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-sd	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-sd /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-sd

taginfo-na-us-tn:
	# make GDNAME=north-america taginfo-na-us-tn
	@echo " Start test  na-us-tn :: Tennessee     ::     mapped local port after finishing   127.0.0.1:22060"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-tn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-tn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-tn

taginfo-na-us-tx:
	# make GDNAME=north-america taginfo-na-us-tx
	@echo " Start test  na-us-tx :: Texas     ::     mapped local port after finishing   127.0.0.1:22061"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-tx	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-tx /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-tx

taginfo-na-us-ut:
	# make GDNAME=us-west taginfo-na-us-ut
	@echo " Start test  na-us-ut :: Utah     ::     mapped local port after finishing   127.0.0.1:22062"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-ut	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-ut /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-ut

taginfo-na-us-va:
	# make GDNAME=us-south taginfo-na-us-va
	@echo " Start test  na-us-va :: Virginia     ::     mapped local port after finishing   127.0.0.1:22063"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-va	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-va /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-va

taginfo-na-us-vt:
	# make GDNAME=us-northeast taginfo-na-us-vt
	@echo " Start test  na-us-vt :: Vermont     ::     mapped local port after finishing   127.0.0.1:22064"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-vt	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-vt /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-vt

taginfo-na-us-wa:
	# make GDNAME=us-west taginfo-na-us-wa
	@echo " Start test  na-us-wa :: Washington     ::     mapped local port after finishing   127.0.0.1:22065"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-wa	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-wa /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-wa

taginfo-na-us-wi:
	# make GDNAME=us-midwest taginfo-na-us-wi
	@echo " Start test  na-us-wi :: Wisconsin     ::     mapped local port after finishing   127.0.0.1:22066"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-wi	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-wi /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-wi

taginfo-na-us-wv:
	# make GDNAME=north-america taginfo-na-us-wv
	@echo " Start test  na-us-wv :: West Virginia     ::     mapped local port after finishing   127.0.0.1:22067"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-wv	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-wv /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-wv

taginfo-na-us-wy:
	# make GDNAME=north-america taginfo-na-us-wy
	@echo " Start test  na-us-wy :: Wyoming     ::     mapped local port after finishing   127.0.0.1:22068"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-na-us-wy	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-na-us-wy /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-na-us-wy


# generated : 2018-07-25:09:10