# generated : 2018-07-25:09:37  // template : ./setup/template/Makefile.jinja2

CURRENT_UID:=$(shell echo $$(id -u):$$(id -g))
export CURRENT_UID

down:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose down

clean:
	CURRENT_UID="$$(id -u):$$(id -g)"  docker-compose rm -f -v


taginfo-ru-ru-ad:
	# make GDNAME=south-fed-district taginfo-ru-ru-ad
	@echo " Start test  ru-ru-ad :: Adygea     ::     mapped local port after finishing   127.0.0.1:24001"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-ad	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-ad /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-ad

taginfo-ru-ru-al:
	# make GDNAME=siberian-fed-district taginfo-ru-ru-al
	@echo " Start test  ru-ru-al :: Altai Republic     ::     mapped local port after finishing   127.0.0.1:24002"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-al	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-al /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-al

taginfo-ru-ru-alt:
	# make GDNAME=siberian-fed-district taginfo-ru-ru-alt
	@echo " Start test  ru-ru-alt :: Altai Krai     ::     mapped local port after finishing   127.0.0.1:24003"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-alt	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-alt /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-alt

taginfo-ru-ru-amu:
	# make GDNAME=far-eastern-fed-district taginfo-ru-ru-amu
	@echo " Start test  ru-ru-amu :: Amur Oblast     ::     mapped local port after finishing   127.0.0.1:24004"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-amu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-amu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-amu

taginfo-ru-ru-ark:
	# make GDNAME=russia taginfo-ru-ru-ark
	@echo " Start test  ru-ru-ark :: Arkhangelsk Oblast     ::     mapped local port after finishing   127.0.0.1:24005"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-ark	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-ark /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-ark

taginfo-ru-ru-ast:
	# make GDNAME=south-fed-district taginfo-ru-ru-ast
	@echo " Start test  ru-ru-ast :: Astrakhan Oblast     ::     mapped local port after finishing   127.0.0.1:24006"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-ast	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-ast /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-ast

taginfo-ru-ru-ba:
	# make GDNAME=volga-fed-district taginfo-ru-ru-ba
	@echo " Start test  ru-ru-ba :: Bashkortostan     ::     mapped local port after finishing   127.0.0.1:24007"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-ba	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-ba /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-ba

taginfo-ru-ru-bel:
	# make GDNAME=central-fed-district taginfo-ru-ru-bel
	@echo " Start test  ru-ru-bel :: Belgorod Oblast     ::     mapped local port after finishing   127.0.0.1:24008"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-bel	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-bel /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-bel

taginfo-ru-ru-bry:
	# make GDNAME=central-fed-district taginfo-ru-ru-bry
	@echo " Start test  ru-ru-bry :: Bryansk Oblast     ::     mapped local port after finishing   127.0.0.1:24009"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-bry	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-bry /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-bry

taginfo-ru-ru-bu:
	# make GDNAME=siberian-fed-district taginfo-ru-ru-bu
	@echo " Start test  ru-ru-bu :: Buryatia     ::     mapped local port after finishing   127.0.0.1:24010"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-bu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-bu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-bu

taginfo-ru-ru-ce:
	# make GDNAME=north-caucasus-fed-district taginfo-ru-ru-ce
	@echo " Start test  ru-ru-ce :: Chechnya     ::     mapped local port after finishing   127.0.0.1:24011"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-ce	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-ce /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-ce

taginfo-ru-ru-che:
	# make GDNAME=ural-fed-district taginfo-ru-ru-che
	@echo " Start test  ru-ru-che :: Chelyabinsk Oblast     ::     mapped local port after finishing   127.0.0.1:24012"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-che	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-che /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-che

taginfo-ru-ru-chu:
	# make GDNAME=russia taginfo-ru-ru-chu
	@echo " Start test  ru-ru-chu :: Chukotka Autonomous Okrug     ::     mapped local port after finishing   127.0.0.1:24013"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-chu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-chu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-chu

taginfo-ru-ru-cr:
	# make GDNAME=crimean-fed-district taginfo-ru-ru-cr
	@echo " Start test  ru-ru-cr :: Republic of Crimea     ::     mapped local port after finishing   127.0.0.1:24014"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-cr	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-cr /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-cr

taginfo-ru-ru-cu:
	# make GDNAME=volga-fed-district taginfo-ru-ru-cu
	@echo " Start test  ru-ru-cu :: Chuvashia     ::     mapped local port after finishing   127.0.0.1:24015"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-cu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-cu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-cu

taginfo-ru-ru-da:
	# make GDNAME=north-caucasus-fed-district taginfo-ru-ru-da
	@echo " Start test  ru-ru-da :: Dagestan     ::     mapped local port after finishing   127.0.0.1:24016"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-da	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-da /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-da

taginfo-ru-ru-in:
	# make GDNAME=north-caucasus-fed-district taginfo-ru-ru-in
	@echo " Start test  ru-ru-in :: Ingushetia     ::     mapped local port after finishing   127.0.0.1:24017"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-in	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-in /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-in

taginfo-ru-ru-irk:
	# make GDNAME=siberian-fed-district taginfo-ru-ru-irk
	@echo " Start test  ru-ru-irk :: Irkutsk Oblast     ::     mapped local port after finishing   127.0.0.1:24018"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-irk	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-irk /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-irk

taginfo-ru-ru-iva:
	# make GDNAME=central-fed-district taginfo-ru-ru-iva
	@echo " Start test  ru-ru-iva :: Ivanovo Oblast     ::     mapped local port after finishing   127.0.0.1:24019"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-iva	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-iva /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-iva

taginfo-ru-ru-kam:
	# make GDNAME=far-eastern-fed-district taginfo-ru-ru-kam
	@echo " Start test  ru-ru-kam :: Kamchatka Krai     ::     mapped local port after finishing   127.0.0.1:24020"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kam	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kam /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kam

taginfo-ru-ru-kb:
	# make GDNAME=north-caucasus-fed-district taginfo-ru-ru-kb
	@echo " Start test  ru-ru-kb :: Kabardino-Balkaria     ::     mapped local port after finishing   127.0.0.1:24021"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kb	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kb /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kb

taginfo-ru-ru-kc:
	# make GDNAME=north-caucasus-fed-district taginfo-ru-ru-kc
	@echo " Start test  ru-ru-kc :: Karachay-Cherkessia     ::     mapped local port after finishing   127.0.0.1:24022"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kc	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kc /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kc

taginfo-ru-ru-kda:
	# make GDNAME=south-fed-district taginfo-ru-ru-kda
	@echo " Start test  ru-ru-kda :: Krasnodar Krai     ::     mapped local port after finishing   127.0.0.1:24023"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kda	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kda /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kda

taginfo-ru-ru-kem:
	# make GDNAME=siberian-fed-district taginfo-ru-ru-kem
	@echo " Start test  ru-ru-kem :: Kemerovo Oblast     ::     mapped local port after finishing   127.0.0.1:24024"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kem	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kem /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kem

taginfo-ru-ru-kgd:
	# make GDNAME=kaliningrad taginfo-ru-ru-kgd
	@echo " Start test  ru-ru-kgd :: Kaliningrad     ::     mapped local port after finishing   127.0.0.1:24025"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kgd	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kgd /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kgd

taginfo-ru-ru-kgn:
	# make GDNAME=ural-fed-district taginfo-ru-ru-kgn
	@echo " Start test  ru-ru-kgn :: Kurgan Oblast     ::     mapped local port after finishing   127.0.0.1:24026"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kgn	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kgn /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kgn

taginfo-ru-ru-kha:
	# make GDNAME=far-eastern-fed-district taginfo-ru-ru-kha
	@echo " Start test  ru-ru-kha :: Khabarovsk Krai     ::     mapped local port after finishing   127.0.0.1:24027"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kha	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kha /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kha

taginfo-ru-ru-khm:
	# make GDNAME=ural-fed-district taginfo-ru-ru-khm
	@echo " Start test  ru-ru-khm :: Khanty-Mansiysk Autonomous Okrug – Ugra     ::     mapped local port after finishing   127.0.0.1:24028"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-khm	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-khm /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-khm

taginfo-ru-ru-kir:
	# make GDNAME=russia taginfo-ru-ru-kir
	@echo " Start test  ru-ru-kir :: Kirov Oblast     ::     mapped local port after finishing   127.0.0.1:24029"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kir	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kir /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kir

taginfo-ru-ru-kk:
	# make GDNAME=siberian-fed-district taginfo-ru-ru-kk
	@echo " Start test  ru-ru-kk :: Republic of Khakassia     ::     mapped local port after finishing   127.0.0.1:24030"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kk	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kk /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kk

taginfo-ru-ru-kl:
	# make GDNAME=russia taginfo-ru-ru-kl
	@echo " Start test  ru-ru-kl :: Kalmykia     ::     mapped local port after finishing   127.0.0.1:24031"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kl	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kl /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kl

taginfo-ru-ru-klu:
	# make GDNAME=central-fed-district taginfo-ru-ru-klu
	@echo " Start test  ru-ru-klu :: Kaluga Oblast     ::     mapped local port after finishing   127.0.0.1:24032"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-klu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-klu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-klu

taginfo-ru-ru-ko:
	# make GDNAME=northwestern-fed-district taginfo-ru-ru-ko
	@echo " Start test  ru-ru-ko :: Komi Republic     ::     mapped local port after finishing   127.0.0.1:24033"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-ko	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-ko /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-ko

taginfo-ru-ru-kos:
	# make GDNAME=central-fed-district taginfo-ru-ru-kos
	@echo " Start test  ru-ru-kos :: Kostroma Oblast     ::     mapped local port after finishing   127.0.0.1:24034"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kos	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kos /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kos

taginfo-ru-ru-kr:
	# make GDNAME=northwestern-fed-district taginfo-ru-ru-kr
	@echo " Start test  ru-ru-kr :: Republic of Karelia     ::     mapped local port after finishing   127.0.0.1:24035"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kr	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kr /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kr

taginfo-ru-ru-krs:
	# make GDNAME=central-fed-district taginfo-ru-ru-krs
	@echo " Start test  ru-ru-krs :: Kursk Oblast     ::     mapped local port after finishing   127.0.0.1:24036"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-krs	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-krs /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-krs

taginfo-ru-ru-kya:
	# make GDNAME=russia taginfo-ru-ru-kya
	@echo " Start test  ru-ru-kya :: Krasnoyarsk Krai     ::     mapped local port after finishing   127.0.0.1:24037"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-kya	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-kya /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-kya

taginfo-ru-ru-len:
	# make GDNAME=northwestern-fed-district taginfo-ru-ru-len
	@echo " Start test  ru-ru-len :: Leningrad oblast     ::     mapped local port after finishing   127.0.0.1:24038"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-len	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-len /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-len

taginfo-ru-ru-lip:
	# make GDNAME=central-fed-district taginfo-ru-ru-lip
	@echo " Start test  ru-ru-lip :: Lipetsk Oblast     ::     mapped local port after finishing   127.0.0.1:24039"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-lip	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-lip /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-lip

taginfo-ru-ru-mag:
	# make GDNAME=far-eastern-fed-district taginfo-ru-ru-mag
	@echo " Start test  ru-ru-mag :: Magadan Oblast     ::     mapped local port after finishing   127.0.0.1:24040"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-mag	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-mag /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-mag

taginfo-ru-ru-me:
	# make GDNAME=volga-fed-district taginfo-ru-ru-me
	@echo " Start test  ru-ru-me :: Mari El     ::     mapped local port after finishing   127.0.0.1:24041"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-me	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-me /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-me

taginfo-ru-ru-mo:
	# make GDNAME=volga-fed-district taginfo-ru-ru-mo
	@echo " Start test  ru-ru-mo :: Republic of Mordovia     ::     mapped local port after finishing   127.0.0.1:24042"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-mo	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-mo /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-mo

taginfo-ru-ru-mos:
	# make GDNAME=central-fed-district taginfo-ru-ru-mos
	@echo " Start test  ru-ru-mos :: Moscow Oblast     ::     mapped local port after finishing   127.0.0.1:24043"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-mos	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-mos /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-mos

taginfo-ru-ru-mow:
	# make GDNAME=central-fed-district taginfo-ru-ru-mow
	@echo " Start test  ru-ru-mow :: Moscow     ::     mapped local port after finishing   127.0.0.1:24044"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-mow	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-mow /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-mow

taginfo-ru-ru-mur:
	# make GDNAME=northwestern-fed-district taginfo-ru-ru-mur
	@echo " Start test  ru-ru-mur :: Murmansk Oblast     ::     mapped local port after finishing   127.0.0.1:24045"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-mur	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-mur /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-mur

taginfo-ru-ru-nen:
	# make GDNAME=northwestern-fed-district taginfo-ru-ru-nen
	@echo " Start test  ru-ru-nen :: Nenets Autonomous Okrug     ::     mapped local port after finishing   127.0.0.1:24046"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-nen	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-nen /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-nen

taginfo-ru-ru-ngr:
	# make GDNAME=northwestern-fed-district taginfo-ru-ru-ngr
	@echo " Start test  ru-ru-ngr :: Novgorod Oblast     ::     mapped local port after finishing   127.0.0.1:24047"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-ngr	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-ngr /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-ngr

taginfo-ru-ru-niz:
	# make GDNAME=volga-fed-district taginfo-ru-ru-niz
	@echo " Start test  ru-ru-niz :: Nizhny Novgorod Oblast     ::     mapped local port after finishing   127.0.0.1:24048"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-niz	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-niz /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-niz

taginfo-ru-ru-nvs:
	# make GDNAME=siberian-fed-district taginfo-ru-ru-nvs
	@echo " Start test  ru-ru-nvs :: Novosibirsk Oblast     ::     mapped local port after finishing   127.0.0.1:24049"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-nvs	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-nvs /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-nvs

taginfo-ru-ru-oms:
	# make GDNAME=siberian-fed-district taginfo-ru-ru-oms
	@echo " Start test  ru-ru-oms :: Omsk Oblast     ::     mapped local port after finishing   127.0.0.1:24050"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-oms	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-oms /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-oms

taginfo-ru-ru-ore:
	# make GDNAME=volga-fed-district taginfo-ru-ru-ore
	@echo " Start test  ru-ru-ore :: Orenburg Oblast     ::     mapped local port after finishing   127.0.0.1:24051"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-ore	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-ore /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-ore

taginfo-ru-ru-orl:
	# make GDNAME=central-fed-district taginfo-ru-ru-orl
	@echo " Start test  ru-ru-orl :: Oryol Oblast     ::     mapped local port after finishing   127.0.0.1:24052"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-orl	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-orl /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-orl

taginfo-ru-ru-per:
	# make GDNAME=volga-fed-district taginfo-ru-ru-per
	@echo " Start test  ru-ru-per :: Perm Krai     ::     mapped local port after finishing   127.0.0.1:24053"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-per	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-per /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-per

taginfo-ru-ru-pnz:
	# make GDNAME=volga-fed-district taginfo-ru-ru-pnz
	@echo " Start test  ru-ru-pnz :: Penza Oblast     ::     mapped local port after finishing   127.0.0.1:24054"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-pnz	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-pnz /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-pnz

taginfo-ru-ru-pri:
	# make GDNAME=far-eastern-fed-district taginfo-ru-ru-pri
	@echo " Start test  ru-ru-pri :: Primorsky Krai     ::     mapped local port after finishing   127.0.0.1:24055"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-pri	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-pri /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-pri

taginfo-ru-ru-psk:
	# make GDNAME=northwestern-fed-district taginfo-ru-ru-psk
	@echo " Start test  ru-ru-psk :: Pskov Oblast     ::     mapped local port after finishing   127.0.0.1:24056"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-psk	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-psk /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-psk

taginfo-ru-ru-ros:
	# make GDNAME=south-fed-district taginfo-ru-ru-ros
	@echo " Start test  ru-ru-ros :: Rostov Oblast     ::     mapped local port after finishing   127.0.0.1:24057"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-ros	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-ros /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-ros

taginfo-ru-ru-rya:
	# make GDNAME=central-fed-district taginfo-ru-ru-rya
	@echo " Start test  ru-ru-rya :: Ryazan Oblast     ::     mapped local port after finishing   127.0.0.1:24058"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-rya	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-rya /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-rya

taginfo-ru-ru-sa:
	# make GDNAME=far-eastern-fed-district taginfo-ru-ru-sa
	@echo " Start test  ru-ru-sa :: Sakha Republic     ::     mapped local port after finishing   127.0.0.1:24059"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-sa	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-sa /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-sa

taginfo-ru-ru-sak:
	# make GDNAME=far-eastern-fed-district taginfo-ru-ru-sak
	@echo " Start test  ru-ru-sak :: Sakhalin Oblast     ::     mapped local port after finishing   127.0.0.1:24060"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-sak	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-sak /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-sak

taginfo-ru-ru-sam:
	# make GDNAME=volga-fed-district taginfo-ru-ru-sam
	@echo " Start test  ru-ru-sam :: Samara Oblast     ::     mapped local port after finishing   127.0.0.1:24061"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-sam	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-sam /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-sam

taginfo-ru-ru-sar:
	# make GDNAME=volga-fed-district taginfo-ru-ru-sar
	@echo " Start test  ru-ru-sar :: Saratov Oblast     ::     mapped local port after finishing   127.0.0.1:24062"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-sar	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-sar /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-sar

taginfo-ru-ru-se:
	# make GDNAME=north-caucasus-fed-district taginfo-ru-ru-se
	@echo " Start test  ru-ru-se :: North Ossetia–Alania     ::     mapped local port after finishing   127.0.0.1:24063"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-se	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-se /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-se

taginfo-ru-ru-sev:
	# make GDNAME=crimean-fed-district taginfo-ru-ru-sev
	@echo " Start test  ru-ru-sev :: Sevastopol     ::     mapped local port after finishing   127.0.0.1:24064"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-sev	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-sev /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-sev

taginfo-ru-ru-smo:
	# make GDNAME=central-fed-district taginfo-ru-ru-smo
	@echo " Start test  ru-ru-smo :: Smolensk Oblast     ::     mapped local port after finishing   127.0.0.1:24065"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-smo	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-smo /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-smo

taginfo-ru-ru-spe:
	# make GDNAME=northwestern-fed-district taginfo-ru-ru-spe
	@echo " Start test  ru-ru-spe :: Saint Petersburg     ::     mapped local port after finishing   127.0.0.1:24066"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-spe	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-spe /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-spe

taginfo-ru-ru-sta:
	# make GDNAME=russia taginfo-ru-ru-sta
	@echo " Start test  ru-ru-sta :: Stavropol Krai     ::     mapped local port after finishing   127.0.0.1:24067"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-sta	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-sta /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-sta

taginfo-ru-ru-sve:
	# make GDNAME=ural-fed-district taginfo-ru-ru-sve
	@echo " Start test  ru-ru-sve :: Sverdlovsk Oblast     ::     mapped local port after finishing   127.0.0.1:24068"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-sve	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-sve /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-sve

taginfo-ru-ru-ta:
	# make GDNAME=volga-fed-district taginfo-ru-ru-ta
	@echo " Start test  ru-ru-ta :: Tatarstan     ::     mapped local port after finishing   127.0.0.1:24069"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-ta	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-ta /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-ta

taginfo-ru-ru-tam:
	# make GDNAME=central-fed-district taginfo-ru-ru-tam
	@echo " Start test  ru-ru-tam :: Tambov Oblast     ::     mapped local port after finishing   127.0.0.1:24070"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-tam	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-tam /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-tam

taginfo-ru-ru-tom:
	# make GDNAME=siberian-fed-district taginfo-ru-ru-tom
	@echo " Start test  ru-ru-tom :: Tomsk Oblast     ::     mapped local port after finishing   127.0.0.1:24071"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-tom	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-tom /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-tom

taginfo-ru-ru-tul:
	# make GDNAME=central-fed-district taginfo-ru-ru-tul
	@echo " Start test  ru-ru-tul :: Tula Oblast     ::     mapped local port after finishing   127.0.0.1:24072"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-tul	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-tul /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-tul

taginfo-ru-ru-tve:
	# make GDNAME=central-fed-district taginfo-ru-ru-tve
	@echo " Start test  ru-ru-tve :: Tver Oblast     ::     mapped local port after finishing   127.0.0.1:24073"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-tve	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-tve /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-tve

taginfo-ru-ru-ty:
	# make GDNAME=siberian-fed-district taginfo-ru-ru-ty
	@echo " Start test  ru-ru-ty :: Tuva Republic     ::     mapped local port after finishing   127.0.0.1:24074"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-ty	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-ty /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-ty

taginfo-ru-ru-tyu:
	# make GDNAME=russia taginfo-ru-ru-tyu
	@echo " Start test  ru-ru-tyu :: Tyumen Oblast     ::     mapped local port after finishing   127.0.0.1:24075"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-tyu	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-tyu /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-tyu

taginfo-ru-ru-ud:
	# make GDNAME=volga-fed-district taginfo-ru-ru-ud
	@echo " Start test  ru-ru-ud :: Udmurtia     ::     mapped local port after finishing   127.0.0.1:24076"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-ud	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-ud /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-ud

taginfo-ru-ru-uly:
	# make GDNAME=volga-fed-district taginfo-ru-ru-uly
	@echo " Start test  ru-ru-uly :: Ulyanovsk Oblast     ::     mapped local port after finishing   127.0.0.1:24077"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-uly	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-uly /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-uly

taginfo-ru-ru-vgg:
	# make GDNAME=russia taginfo-ru-ru-vgg
	@echo " Start test  ru-ru-vgg :: Volgograd Oblast     ::     mapped local port after finishing   127.0.0.1:24078"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-vgg	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-vgg /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-vgg

taginfo-ru-ru-vla:
	# make GDNAME=central-fed-district taginfo-ru-ru-vla
	@echo " Start test  ru-ru-vla :: Vladimir Oblast     ::     mapped local port after finishing   127.0.0.1:24079"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-vla	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-vla /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-vla

taginfo-ru-ru-vlg:
	# make GDNAME=northwestern-fed-district taginfo-ru-ru-vlg
	@echo " Start test  ru-ru-vlg :: Vologda Oblast     ::     mapped local port after finishing   127.0.0.1:24080"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-vlg	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-vlg /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-vlg

taginfo-ru-ru-vor:
	# make GDNAME=central-fed-district taginfo-ru-ru-vor
	@echo " Start test  ru-ru-vor :: Voronezh Oblast     ::     mapped local port after finishing   127.0.0.1:24081"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-vor	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-vor /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-vor

taginfo-ru-ru-yan:
	# make GDNAME=ural-fed-district taginfo-ru-ru-yan
	@echo " Start test  ru-ru-yan :: Yamalo-Nenets Autonomous Okrug     ::     mapped local port after finishing   127.0.0.1:24082"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-yan	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-yan /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-yan

taginfo-ru-ru-yar:
	# make GDNAME=central-fed-district taginfo-ru-ru-yar
	@echo " Start test  ru-ru-yar :: Yaroslavl Oblast     ::     mapped local port after finishing   127.0.0.1:24083"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-yar	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-yar /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-yar

taginfo-ru-ru-yev:
	# make GDNAME=far-eastern-fed-district taginfo-ru-ru-yev
	@echo " Start test  ru-ru-yev :: Jewish Autonomous Oblast     ::     mapped local port after finishing   127.0.0.1:24084"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-yev	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-yev /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-yev

taginfo-ru-ru-zab:
	# make GDNAME=siberian-fed-district taginfo-ru-ru-zab
	@echo " Start test  ru-ru-zab :: Zabaykalsky Krai     ::     mapped local port after finishing   127.0.0.1:24085"
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up --no-start taginfo-ru-ru-zab	
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose  -f docker-compose-job.yml  run     --rm taginfo-job-ru-ru-zab /osm/sh/startlocal.sh 
	CURRENT_UID="$$(id -u):$$(id -g)" docker-compose up taginfo-ru-ru-zab


# generated : 2018-07-25:09:37