# generated : 2018-07-25:07:01  // template : ./setup/service_down.sh.jinja2

export CURRENT_UID="$(id -u):$(id -g)" 


 docker-compose stop taginfo-as-ae
 docker-compose stop taginfo-as-af
 docker-compose stop taginfo-as-am
 docker-compose stop taginfo-as-az
 docker-compose stop taginfo-as-bd
 docker-compose stop taginfo-as-bh
 docker-compose stop taginfo-as-bn
 docker-compose stop taginfo-as-bt
 docker-compose stop taginfo-as-cn
 docker-compose stop taginfo-as-ge
 docker-compose stop taginfo-as-id
 docker-compose stop taginfo-as-il
 docker-compose stop taginfo-as-in-an
 docker-compose stop taginfo-as-in-ap
 docker-compose stop taginfo-as-in-ar
 docker-compose stop taginfo-as-in-as
 docker-compose stop taginfo-as-in-br
 docker-compose stop taginfo-as-in-ch
 docker-compose stop taginfo-as-in-ct
 docker-compose stop taginfo-as-in-dd
 docker-compose stop taginfo-as-in-dl
 docker-compose stop taginfo-as-in-dn
 docker-compose stop taginfo-as-in-ga
 docker-compose stop taginfo-as-in-gj
 docker-compose stop taginfo-as-in-hp
 docker-compose stop taginfo-as-in-hr
 docker-compose stop taginfo-as-in-jh
 docker-compose stop taginfo-as-in-jk
 docker-compose stop taginfo-as-in-ka
 docker-compose stop taginfo-as-in-kl
 docker-compose stop taginfo-as-in-ld
 docker-compose stop taginfo-as-in-mh
 docker-compose stop taginfo-as-in-ml
 docker-compose stop taginfo-as-in-mn
 docker-compose stop taginfo-as-in-mp
 docker-compose stop taginfo-as-in-mz
 docker-compose stop taginfo-as-in-nl
 docker-compose stop taginfo-as-in-or
 docker-compose stop taginfo-as-in-pb
 docker-compose stop taginfo-as-in-py
 docker-compose stop taginfo-as-in-rj
 docker-compose stop taginfo-as-in-sk
 docker-compose stop taginfo-as-in-tg
 docker-compose stop taginfo-as-in-tn
 docker-compose stop taginfo-as-in-tr
 docker-compose stop taginfo-as-in-up
 docker-compose stop taginfo-as-in-ut
 docker-compose stop taginfo-as-in-wb
 docker-compose stop taginfo-as-io
 docker-compose stop taginfo-as-iq
 docker-compose stop taginfo-as-ir
 docker-compose stop taginfo-as-jo
 docker-compose stop taginfo-as-jp-01
 docker-compose stop taginfo-as-jp-02
 docker-compose stop taginfo-as-jp-03
 docker-compose stop taginfo-as-jp-04
 docker-compose stop taginfo-as-jp-05
 docker-compose stop taginfo-as-jp-06
 docker-compose stop taginfo-as-jp-07
 docker-compose stop taginfo-as-jp-08
 docker-compose stop taginfo-as-jp-09
 docker-compose stop taginfo-as-jp-10
 docker-compose stop taginfo-as-jp-11
 docker-compose stop taginfo-as-jp-12
 docker-compose stop taginfo-as-jp-13
 docker-compose stop taginfo-as-jp-14
 docker-compose stop taginfo-as-jp-15
 docker-compose stop taginfo-as-jp-16
 docker-compose stop taginfo-as-jp-17
 docker-compose stop taginfo-as-jp-18
 docker-compose stop taginfo-as-jp-19
 docker-compose stop taginfo-as-jp-20
 docker-compose stop taginfo-as-jp-21
 docker-compose stop taginfo-as-jp-22
 docker-compose stop taginfo-as-jp-23
 docker-compose stop taginfo-as-jp-24
 docker-compose stop taginfo-as-jp-25
 docker-compose stop taginfo-as-jp-26
 docker-compose stop taginfo-as-jp-27
 docker-compose stop taginfo-as-jp-28
 docker-compose stop taginfo-as-jp-29
 docker-compose stop taginfo-as-jp-30
 docker-compose stop taginfo-as-jp-31
 docker-compose stop taginfo-as-jp-32
 docker-compose stop taginfo-as-jp-33
 docker-compose stop taginfo-as-jp-34
 docker-compose stop taginfo-as-jp-35
 docker-compose stop taginfo-as-jp-36
 docker-compose stop taginfo-as-jp-37
 docker-compose stop taginfo-as-jp-38
 docker-compose stop taginfo-as-jp-39
 docker-compose stop taginfo-as-jp-40
 docker-compose stop taginfo-as-jp-41
 docker-compose stop taginfo-as-jp-42
 docker-compose stop taginfo-as-jp-43
 docker-compose stop taginfo-as-jp-44
 docker-compose stop taginfo-as-jp-45
 docker-compose stop taginfo-as-jp-46
 docker-compose stop taginfo-as-jp-47
 docker-compose stop taginfo-as-kg
 docker-compose stop taginfo-as-kh
 docker-compose stop taginfo-as-kp
 docker-compose stop taginfo-as-kr
 docker-compose stop taginfo-as-kw
 docker-compose stop taginfo-as-kz
 docker-compose stop taginfo-as-la
 docker-compose stop taginfo-as-lb
 docker-compose stop taginfo-as-lk
 docker-compose stop taginfo-as-mm
 docker-compose stop taginfo-as-mn
 docker-compose stop taginfo-as-mv
 docker-compose stop taginfo-as-my
 docker-compose stop taginfo-as-np
 docker-compose stop taginfo-as-om
 docker-compose stop taginfo-as-ph
 docker-compose stop taginfo-as-pk
 docker-compose stop taginfo-as-ps
 docker-compose stop taginfo-as-qa
 docker-compose stop taginfo-as-sa
 docker-compose stop taginfo-as-sg
 docker-compose stop taginfo-as-sy
 docker-compose stop taginfo-as-th
 docker-compose stop taginfo-as-tj
 docker-compose stop taginfo-as-tl
 docker-compose stop taginfo-as-tm
 docker-compose stop taginfo-as-tw
 docker-compose stop taginfo-as-uz
 docker-compose stop taginfo-as-vn
 docker-compose stop taginfo-as-ye
 
# generated : 2018-07-25:07:01